### ISSUE TITLE
Use of unresolved identifier 'JSONEncoding' Swift 4 [POST Request]

### ISSUE THREAD

**Issue by sam0829** [RxSwiftCommunity/RxAlamofire#100]
Hello, I am trying to do a POST request with RxAlamofire but I get an error here. I didn't find any POST example in the sample even. I am doing following:

```
func someFunction() -> Observable<Bool> {
return Observable<Bool>.create { observer in
            RxAlamofire.requestJSON(.post, ApiConstants.MY_URL, parameters: nil, encoding: JSONEncoding.default, headers: nil)
                .subscribe(onNext: { (r,json) in
                                        
                }, onError: { error in
                    observer.onError(error)
                })
        }

}
```
But I get an error saying Use of unresolved identifier 'JSONEncoding' Swift 4. Please let me know how can I do POST request?

**Comment by sunshinejr** [comment]
@sam0829 Did you import `Alamofire` at the top of your file? If that's correct, please post your `Podfile.lock` here.

**Comment by freak4pc** [comment]
Encoding is of type `URLEncoding`, not `JSONEncoding` : https://github.com/RxSwiftCommunity/RxAlamofire/blob/c2fdccf8058d1a61f5fbb540054c21372de1151d/Sources/RxAlamofire.swift#L248

**Comment by sunshinejr** [comment]
@freak4pc `URLEncoding.default` is just the default argument. As far as I remember`JSONEncoding.default` is a valid argument as it should implement `ParameterEncoding` as well.

**Comment by sam0829** [comment]
Yes, importing `Alamofire` solved the error. Sorry I am pretty new in iOS development & didn't knew JSONEncoding was part of the Alamofire. Thanks for quick reply & btw I had to use `URLEncoding.default` because if I use `JSONEncoding.default`, API was not getting the parameters I passed, but when I used `URLEncoding.default`, API was happy.
