### ISSUE TITLE
build error iOS 11

### ISSUE THREAD

**Issue by 1ckola** [RxSwiftCommunity/RxAlamofire#104]
Does RxAlamofire support iOS 11 build ?

Getting attached error on build
<img width="862" alt="screen shot 2018-02-18 at 5 55 47 pm" src="https://user-images.githubusercontent.com/16364754/36359987-ffd2235a-14d4-11e8-82ef-d7e81dc38d29.png">

**Comment by freak4pc** [comment]
@1ckola I'm not seeing any issue on my end. Any chance you can pack this issue in a reproducible project so I can take a look? 

<img width="854" alt="8ff2a749-8f11-4b6c-9766-a3a5cbefa817" src="https://user-images.githubusercontent.com/605076/36370643-1b9f1e7e-1568-11e8-9a6d-d44e2217fdb4.png">

**Comment by bobgodwinx** [comment]
@1ckola `.next` take one argument as parameter so if you wrap it into a tuple that should be fine just like @freak4pc did on line `776`

**Comment by freak4pc** [comment]
@bobgodwinx It's part of the library code, not his own. That's why I'm not sure why its not compiling for him.

**Comment by 1ckola** [comment]
Thank you very much, wrapping it into a tuple worked
