### ISSUE TITLE
- noManifest - Updating library with Package Manager

### ISSUE THREAD

**Issue by jesusmfdez** [RxSwiftCommunity/RxAlamofire#106]
I've this issue when I am trying to configure RxAlamofire in Package Manager:

**error: noManifest(baseURL: "https://github.com/RxSwiftCommunity/RxAlamofire.git", version: Optional("4.0.0"))**

I was taking a look the issues and this  #102 says that RxAlamofire supports Package Manager.

Thank you in advance, regards!

**Comment by freak4pc** [comment]
There was an issue fixed yesterday in #105 
Can you confirm if the issue still occurs for you ?

**Comment by jesusmfdez** [comment]
Thank you for answer fastly.

I took a look this issue, but yes... I continue getting the same problem.

I removed other libraries to avoid conflict problems or something like that. I paste here a couple of screenshot for if it's helpful for you.

**Thank you so much again**!

![captura de pantalla 2018-02-26 a las 14 01 53](https://user-images.githubusercontent.com/9450348/36672051-2b8fcaf4-1afe-11e8-9bda-98558db38171.png)
![captura de pantalla 2018-02-26 a las 14 01 33](https://user-images.githubusercontent.com/9450348/36672054-2eb7486a-1afe-11e8-8841-30d884a80037.png)

**Comment by freak4pc** [comment]
I'll probably have to push a new tag out. I'll take care of this soon, leaving this issue open so I don't forget :)

**Comment by freak4pc** [comment]
@jesusmfdez Can you try again please?

**Comment by jesusmfdez** [comment]
It's working now!!
Thank you @freak4pc

**Comment by freak4pc** [comment]
Glad to hear :)
