### ISSUE TITLE
Json response as Data

### ISSUE THREAD

**Issue by tatimagdalena** [RxSwiftCommunity/RxAlamofire#107]
Hi!
When requesting a JSON, is there any way I can get the json as a Data object, instead of a dictionary?
Alamofire does so, and it is better to work with Data when using Codable protocol.

**Comment by freak4pc** [comment]
Hey @tatimagdalena, You can use `responseData()` :) 
https://github.com/RxSwiftCommunity/RxAlamofire/blob/master/Sources/RxAlamofire.swift#L759
