### ISSUE TITLE
DownloadRequest is missing progress observable.

### ISSUE THREAD

**Issue by TobiasRe** [RxSwiftCommunity/RxAlamofire#110]
The progress observable was removed from `DownloadRequest` in release 4.1.0

This is the commit causing the issue:
[Unify Upload & Download progress handling](https://github.com/RxSwiftCommunity/RxAlamofire/commit/c4c4c13c12ef25a24b5eb51feaca108621133dcc)

We should bring the progress back.

**Comment by freak4pc** [comment]
Hey @TobiasRe. I committed that code. 

`progress()` now lives in `DataRequest` - and `DownloadRequest` extends `DataRequest`. 

For that reason, progress() is available on `DownloadRequest` and `UploadRequest` using that code. Are you seeing different results?

**Comment by TobiasRe** [comment]
Thanks for the quick response @freak4pc!

I checked that and in Alamofire 4.7.1 `DownloadRequest` inherits from `Request`

[open class DownloadRequest: Request](https://github.com/Alamofire/Alamofire/blob/10323991876208d196c6d1bf91beeb2ec4383b27/Source/Request.swift#L423)

Which Alamofire version are you using?

**Comment by freak4pc** [comment]
@TobiasRe uhm that's interesting :) 
Luckily, though, `DataRequest` is actually a `Request` itself: https://github.com/Alamofire/Alamofire/blob/10323991876208d196c6d1bf91beeb2ec4383b27/Source/Request.swift#L356

We might be able to just get away with changing the base to Request but I'm not sure off the top of my head. would you mind trying on your local code?

**Comment by freak4pc** [comment]
Can you try this branch : https://github.com/RxSwiftCommunity/RxAlamofire/tree/fix/unified-progress

@TobiasRe

**Comment by TobiasRe** [comment]
You're fast!

Build was successful!
Looking forward to a new release. :)

**Comment by freak4pc** [comment]
Fixed in 4.2.0
