### ISSUE TITLE
204 - No content causing serialization crashes

### ISSUE THREAD

**Issue by foxware00** [RxSwiftCommunity/RxAlamofire#112]
I have an issue when I receive a 204 with no content. The same endpoint can return 200 with content and all the appropriate errors. So I validate `request.validate(statusCode: 200..<300).rx.responseData()` however when I get a 204 it crashes. This is still a valid case and should go to `onNext`. Is there anyway I can achieve this or am I missing something?

I get the following error -
`dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "No value." UserInfo={NSDebugDescription=No value.})))`

**Comment by freak4pc** [comment]
Hey @foxware00 - Can you provide a reproducible project? I'd love to take a look for you.

**Comment by foxware00** [comment]
I'm trying to come up with way to use any object type in the response. I don't think my solution is quite thorough enough. I can probably adjust my interface to allow optional responses. Or I guess a wrapper like a tuple Result<Code, T?> 🤔 

Either way this is how I make a request. It's designed to be as generic as possible so I can serialized whichever objects I want. I can obviously handle if `jsonData` isn't valid json here. but then my entire interface needs to propagate optional responses. I suppose this is an issue with the way I have this configured. This will be a problem with any creation endpoints, this case is specific because it used both. 
```
func makeRequest<T: Codable>(request: ApiRequest, responseType: T.Type) -> Observable<T> {
        return sessionManager
                .rx
                .responseData(request)
                .responseObject(type: responseType)
    }
```

This is my extension

```
extension ObservableType {

    public func responseObject<T: Codable>(type: T.Type) -> Observable<T> {
        return flatMap { data -> Observable<T> in
            let responseTuple = data as? (HTTPURLResponse, Data)

            guard let jsonData = responseTuple?.1 else {
                throw NSError(domain: "",
                        code: -1,
                        userInfo: [NSLocalizedDescriptionKey: "Could not decode object"])
            }

            let decoder = JSONDecoder()
            var object: T?
            do {
                object = try? decoder.decode(type, from: jsonData)
            } catch {
                object = nil
            }

            return Observable.just(object)
        }
    }    
}

extension Reactive where Base: Alamofire.SessionManager {

    func responseData(_ urlRequest: URLRequestConvertible) -> Observable<(HTTPURLResponse, Data)> {
        return request(urlRequest: urlRequest)
                .flatMap { request in
                    return request.validate(statusCode: 200..<300)
                            .rx.responseData()
                }.subscribeOn(Schedulers.utility)
    }
}
```

**Comment by freak4pc** [comment]
Hey, sorry off I wasn't obvious :) 
My point was - If you could provide a demo Xcode project I can run to get the crash your experiencing, that would highly help in resolving your issue. I want to make sure the crash is indeed RxAlamofire related and not related to your own code base.

Thanks !

**Comment by foxware00** [comment]
Sorry, i've confirmed it was a problem on my side. I've gone with down the route of wrapping the optional type in a `Result<Code, T?>` for these cases

**Comment by freak4pc** [comment]
No worries. thanks !
