### ISSUE TITLE
Multiple Memory leak 

### ISSUE THREAD

**Issue by nija78** [RxSwiftCommunity/RxAlamofire#117]
![screen shot 2018-05-16 at 10 08 20](https://user-images.githubusercontent.com/17722719/40104654-3548f8aa-58f1-11e8-8b78-633e8c646c99.png)
![screen shot 2018-05-16 at 10 08 07](https://user-images.githubusercontent.com/17722719/40104655-356246c0-58f1-11e8-82e1-b2e364f8d365.png)
![screen shot 2018-05-16 at 10 07 26](https://user-images.githubusercontent.com/17722719/40104656-357a03d2-58f1-11e8-878f-ce303241b232.png)
hello, 
I have multiple memory link in RXalamofire see picture.
thank's

**Comment by freak4pc** [comment]
Hey @nija78 

Can you validate this isn't an issue with Alamofire itself?
