### ISSUE TITLE
Xcode 10 Compatibility

### ISSUE THREAD

**Issue by munirwanis** [RxSwiftCommunity/RxAlamofire#118]
The project does not work with Xcode 10, it looks like it's a problem with RxCocoa, the Cartfile is also using a old version of Alamofire and RxSwift.

**Comment by freak4pc** [comment]
Hey @munirwanis - We usually don't bump dependencies to such early builds of Xcode (but closer to GM) as it requires a lot of work and its easier than chasing a moving target.

I believe there's a `Xcode10` branch on RxCocoa if you'd like to try that.

Shai
