### ISSUE TITLE
Please tell me how to set time out for request?

### ISSUE THREAD

**Issue by duyanpham** [RxSwiftCommunity/RxAlamofire#119]

**Comment by freak4pc** [comment]
@duyanpham This is an Alamofire question, not an RxAlamofire question.

**Comment by duyanpham** [comment]
I used all the ways to set time out of Alamofire, but It 's not work.

**Comment by freak4pc** [comment]
Does it work in Alamofire itself, but not in RxAlamofire ? 
If it doesn't work well in Alamofire you should open an issue in there repo, as this is only a Reactive wrapper for it.
