### ISSUE TITLE
POST binary data

### ISSUE THREAD

**Issue by brunoescalona** [RxSwiftCommunity/RxAlamofire#120]
I would like to post binary data through RxAlamofire but after some days of research and tries, I'm not able to do it.

Here you can find the POSTMAN example of the request that I am trying to reproduce with RxAlamofire:

![captura de pantalla 2018-08-20 a las 13 42 36](https://user-images.githubusercontent.com/23025266/44338744-3b731600-a47f-11e8-8f50-4c1ef8f91202.png)
![captura de pantalla 2018-08-20 a las 13 42 48](https://user-images.githubusercontent.com/23025266/44338761-44fc7e00-a47f-11e8-865f-b5294a753c55.png)

Is a post method with the Authorization and Content-Type headers and the binary data attached.

I have tried to find some example or something related but I couldn't find a solution. I could just find multipart form data examples but with multipart form data the server doesn't work (is a external API)

If someone could guide me or show me some example code.

Thank you! :)

**Comment by brunoescalona** [comment]
Hi @freak4pc 
I could achieve the behaviour that I wanted with the following function:
```
public func upload(media: Data) -> Observable<ContentUri> {
        let headers = [
            "content-type": "image/png",
            "authorization": Defaults.getAuthorizationToken()
        ]
        return Observable<ContentUri>.create({observer in
            Alamofire.upload(media, to: "\(APIConstants.ProductionServer.baseURL)media/upload", headers: headers)
                .validate()
                .responseJSON{ (dataResponse) in
                    if dataResponse.result.isSuccess {
                        observer.onNext(Mapper<ContentUri>().map(JSONObject:dataResponse.result.value)!)
                        observer.onCompleted()
                    }else{
                        observer.onError(dataResponse.result.error!)
                    }
                    
                }
            return Disposables.create();
        })
    }
```
Where `ContentUri` is just a class to parse the response

The problem is that I would like to implement the same function `func upload(media: Data) -> Observable<ContentUri>` but with RxAlamofrie.

Thanks for your help

**Comment by freak4pc** [comment]
Seems like this issue wasn't related to RxAlamofire to begin with:) 
It's usually better to read the official Alamofire documentation since this repo is merely a tiny wrapper around it. Glad you got your issue worked out!
