### ISSUE TITLE
Build failed in iOS 12

### ISSUE THREAD

**Issue by piotrbcz** [RxSwiftCommunity/RxAlamofire#123]
While building the "RxAlamofire-iOS" by Cathage, it's failed as "Task failed with exit code 65: ..."

**Comment by red282** [comment]
I guess there is an issue with tvOS target. When I build with a `--platform iOS` option, it fails with an error message that both tvOS and iOS do something. But when I use a `--platform tvOS` option, there is no error.

**Comment by piotrbcz** [comment]
I'm using this framework on iOS project, but when I tried to use this framework with Carthage, the build was failed.

**Comment by piotrbcz** [comment]
It worked well on iOS 11.4, but after update iOS, it was failed.

**Comment by red282** [comment]
If urgent, you can use my forked repository. In `Cartfile`, change the `RxAlamofire` repository to `red282/RxAlamofire` and use `xcode-10` branch. For example,

- as-is
  - `github "RxSwiftCommunity/RxAlamofire"` ~> 4.2
- to-be
  - `github "red282/RxAlamofire" "xcode-10"`

This is a temporary expedient. I believe that someone will fix this issue :)

**Comment by gumob** [comment]
@red282 It worked on Xcode 12 and iOS12. 👍

**Comment by freak4pc** [comment]
Fixed in RxAlamofire 4.3

**Comment by piotrbcz** [comment]
Perfect. Working well on iOS 12.
