### ISSUE TITLE
Support Xcode 10.0 and Swift 4.2

### ISSUE THREAD

**Issue by NeverwinterMoon** [RxSwiftCommunity/RxAlamofire#124]
RxSwift moved to 4.3.0 with that support, I would love to see RxAlamofire follow suit.

**Comment by Drusy** [comment]
Carthage build is also failing, this issue seems to be resolved for RxDataSources: https://github.com/RxSwiftCommunity/RxDataSources/issues/237

**Comment by kenji21** [comment]
Following carthage command produces same error as in PR https://github.com/RxSwiftCommunity/RxAlamofire/pull/122 of @rynecheow: 

`carthage build --no-skip-current --no-use-binaries --platform iOS`

Then to fix this, I just removed `RxCocoa.framework`, `RxSwift.framework` and `Alamofire.framework` from `RxAlamofire-iOS` target of `RxAlamofire.xcodeproj`

<img width="825" alt="screen shot" src="https://user-images.githubusercontent.com/1105089/45868503-2ba06780-bd86-11e8-90c4-28c51338e496.png">

The `RxAlamofire-tvOS` is already configured like this:

<img width="855" alt="screen shot 1" src="https://user-images.githubusercontent.com/1105089/45868500-2a6f3a80-bd86-11e8-8411-9f7ff02bd53b.png">


Maybe @rynecheow can update its PR with this modification

**Comment by gonzo-oin** [comment]
The pull request of @rynecheow is working like a charm 👍 
While waiting merge of PR, you could use `github "rynecheow/RxAlamofire" "xcode-10"` in your cartfile

**Comment by freak4pc** [comment]
RxAlamofire 4.3 was just released. Thanks @rynecheow !
