### ISSUE TITLE
Cannot convert value of type 'Data' to type 'HttpResponse<[_]>' in coercion

### ISSUE THREAD

**Issue by alouanemed** [RxSwiftCommunity/RxAlamofire#127]
I am trying to use generics in swift to intrepret http responses. All The Json responses have the same signature at the top : 

    {
    "request": "foo",
    "result": "[{},{}....]
    }

So I am using this : 

    public struct HttpResponse<DATA: Codable>  {
        public let request: Bool?
        public let result: DATA?
        
        enum CodingKeys: String, CodingKey {
            case request= "request"
            case result = "result"
        
         }   ..

In My  Network layer:

    final class Network<T: Decodable> {
     ....
     func getItems(_ path: String) -> Observable<[T]> {
        let absolutePath = "\(endPoint)/\(path)"
        return RxAlamofire
            .data(.get, absolutePath)
            .debug()
            .observeOn(scheduler)
            .map({ httpResponse-> [T] in
                let pResponse : HttpResponse<T>
                if response is HttpResponse<[T]>{
                    pResponse = httpResponse as HttpResponse<[T]>
                }
               
                 return try JSONDecoder().decode([T].self, from: pResponse.data)
            })
    }

The Error I get : 

> Cannot convert value of type 'Data' to type 'HttpResponse<[_]>' in
> coercion

How to have the function return the generic data of HttpResponse?

**Comment by mendesbarreto** [comment]
Hello @alouanemed ,

How is it going? I know there is a lot of time this issue is opened, but I should ask. 

Did you find any solution for your issue? if yes, please share if you could.

If not, Maybe I can help in something =) .

Thank you

**Comment by mendesbarreto** [comment]
I'll close this issue, since it has been open for a long time without interactions, if we need, we can re-open and discuss it.

Thank you!
