### ISSUE TITLE
Support Alamofire 5.0.0

### ISSUE THREAD

**Issue by carlosypunto** [RxSwiftCommunity/RxAlamofire#130]
It may be too early to make this issue, but Alamofire 5 B1 is fully functional and has very good qualities. It seems it's new API is practically defined [as announced on Swift's blog](https://forums.swift.org/t/alamofire-5-one-year-in-the-making-now-in-beta/18865).

There is a [new branch with the beta 1 changes](https://github.com/RxSwiftCommunity/RxAlamofire/tree/supportAlamofire5.0.0.beta.1), whose tests pass, as the start of the migration process and it is fully usable.

If you think well, any future change you can do on that new branch

**Comment by freak4pc** [comment]
Feel free to make a branch with those changes if you'd like to. Otherwise, I think we'll wait for more advanced betas to avoid doing double work. WDYT?

**Comment by sunshinejr** [comment]
@carlosypunto @freak4pc I just started doing the update in Moya, so I'd be happy to help with CRs or anything else here as well.

**Comment by freak4pc** [comment]
I'll appreciate it @sunshinejr ! I usually like to wait longer for final interfaces but there's no harm in starting early here :)

**Comment by sunshinejr** [comment]
@freak4pc yeah we started earlier because the rewrite introduced few aspects around underlying requests that are now **asynchronously** created in Alamofire. This way we will have to rewrite some parts of Moya, not sure if something similar will happen here in RxAlamofire, but I think it's worth to start the works now to make a room for possible rewrite.

That being said, I don't really have time to do it myself, so I offer my help with CRs and such. I might do it later, after getting comfortable with Moya transition, if nobody starts the works.

**Comment by carlosypunto** [comment]
@freak4pc My idea was that, leave this branch to evolve v5 from here, if will be more laborious merge than forget it, that has no problems for me. A although is possible will haven't many changes in Alamofire v5.

**Comment by freak4pc** [comment]
Either sounds great to me. Feel free to open a branch and start playing around :) I would really don't mind.

**Comment by thedavidharris** [comment]
Started playing around with this out of curiosity, it's pretty straightforward outside of the response decoding since there was a big refactor to Codable over some of the existing constructs (https://github.com/Alamofire/Alamofire/pull/2265).

**Comment by phongleq** [comment]
Has there been update to this?

**Comment by danipralea** [comment]
very interested in this as well and I would love to use the Alamofire 5.0 features. are there any plans to support it?

**Comment by sunshinejr** [comment]
@phongleq @danipralea I think we all agree that we would love to support Alamofire 5.0. Now we just need someone to prepare a PR with the update and I will gladly review it 👍

**Comment by michzio** [comment]
Is there any alpha, beta release of RxAlamofire compatible with Alamofire 5.0 i am coding sample project and it will nice to have even beta/alpha pod release

**Comment by sunshinejr** [comment]
@michzio unless someone made a fork and didn’t make a PR yet, we don’t have a version with RxAlamofire that supports Alamofire 5.

**Comment by CodingAleCR** [comment]
https://github.com/RxSwiftCommunity/RxAlamofire/releases/tag/5.2.0

**Comment by hamedmohammadi** [comment]
it looks like in the master branch you removed test targets in "feature/rxswift-alamofire-5.0" branch everything was fine.
should I correct this and send you a pull request or you will fix this?

**Comment by rynecheow** [comment]
Alamofire 5 is already supported.
