### ISSUE TITLE
leak

### ISSUE THREAD

**Issue by manondidi** [RxSwiftCommunity/RxAlamofire#134]
![qq20190210-222122](https://user-images.githubusercontent.com/18095722/52534934-ec999f80-2d82-11e9-8947-4fa73d8a995a.png)

 RxAlamofire.requestString(.post, "http://47.98.129.57:8080/info-admin-web/user/manondidi", parameters: ["password":"12lllkkjj3"], encoding: URLEncoding.default, headers:  ["X-Requested-With": "XMLHttpRequest"])
            .debug()
            .observeOn(MainScheduler.instance)
            .subscribe(onNext: {[weak self] (str) in
                self?.showContent()
                }, onError: {[weak self]  (error) in
                    self?.showError()
            }).disposed(by: disposeBag)

**Comment by freak4pc** [comment]
Hey, please provide a reproducible project or a more substantive example. This isn't a proper bug report :) 

Thanks,
Shai.

**Comment by manondidi** [comment]
have you ever try to use instruments leak to test rxalamofire demo?
it also leaks when i run  rxalamofire-ios-example ,click Get Dummy Data
you can try it,please fix it

你们试过用instruments leak来测试过 rxalamofire demo吗?
当我运行 rxalamofire-ios-example 点击  "Get Dummy Data" 按钮的时候发生了leak
不信你自己试试

**Comment by manondidi** [comment]
do you find it leak and reason?

**Comment by freak4pc** [comment]
Hey - this is a volunteer based project. We don’t work on demand :) 

Feel free to open a PR with the fix if you found it.

**Comment by manondidi** [comment]
okay ,i will try to fix it if i can

**Comment by manondidi** [comment]
hey ,i find leak
because of alamofire
it leaks when i run alamofire 4.0+&5.0 demo

**Comment by freak4pc** [comment]
If it's an issue in Alamofire itself, feel free to file an issue on their repo

**Comment by manondidi** [comment]
the leak is ios 11 bug, not your fault ,
now in ios12.4.3 ,the bug is disappear,it's ok
