### ISSUE TITLE
Unable to build RxAlamofire using Xcode 10.2

### ISSUE THREAD

**Issue by kokhong20** [RxSwiftCommunity/RxAlamofire#137]
Apple has released Xcode 10.2 and I am unable to build RxAlamofire after I updated my Xcode.

`Task failed with exit code 65:
    /usr/bin/xcrun xcodebuild -workspace /Users/jameslai/Git/core-product-ios-client/Carthage/Checkouts/RxAlamofire/RxAlamofire/RxAlamofire.xcworkspace -scheme RxAlamofire-iOS -configuration Release -derivedDataPath /Users/jameslai/Library/Caches/org.carthage.CarthageKit/DerivedData/10.2_10E125/RxAlamofire/4.3.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/vj/_sk8lb7s23l69phls3c_p8340000gp/T/RxAlamofire SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/jameslai/Git/core-product-ios-client/Carthage/Checkouts/RxAlamofire)`

**Comment by afeng159** [comment]
xcode10.2  using swift4.2    isOK？

**Comment by freak4pc** [comment]
RxAlamofire 5.0.0 was just released.
