### ISSUE TITLE
There is no 4.5.0 version in Cocoapods specs

### ISSUE THREAD

**Issue by DevTchernov** [RxSwiftCommunity/RxAlamofire#148]
https://github.com/CocoaPods/Specs/tree/master/Specs/f/8/f/RxAlamofire

**Comment by xPryds** [comment]
Same problem here

**Comment by OrRosenblatt** [comment]
Why was the issue closed? I'm experiencing now the same... :(

<img width="949" alt="Screen Shot 2020-08-19 at 9 24 30 PM" src="https://user-images.githubusercontent.com/20166480/90706081-5fca7e80-e262-11ea-9333-08d9281227d4.png">

**Comment by freak4pc** [comment]
Hey Or, I imagine your local specs aren't updated. Try running `pod update`: 
https://cocoapods.org/pods/RxAlamofire

**Comment by freak4pc** [comment]
So, here's the problem — I can't upload a 4.5 podspec because I need Xcode 10 to do that or `pod trunk push` fails validation. If anyone has an old enough version of Xcode to do this, let me know.

**Comment by rynecheow** [comment]
Hi @OrRosenblatt, this was closed due to inactivity. Are you able to use newer versions?
