### ISSUE TITLE
Cannot get response data when error occurred

### ISSUE THREAD

**Issue by kleiberjp** [RxSwiftCommunity/RxAlamofire#151]
This request Is based on https://github.com/RxSwiftCommunity/RxAlamofire/issues/29

Isn't possible get the status coder or response data when error occurs on a request

**Comment by mesheilah** [comment]
is there any updates to this issue ?

**Comment by gorbat-o** [comment]
hey, same issue here

**Comment by gorbat-o** [comment]
I end up using `.responseData()`

**Comment by freak4pc** [comment]
As mentioned in #29, I'm happy to review a PR if someone makes one. I'm not a user of this repo so fixing this wouldn't be something I can prioritize.

**Comment by gorbat-o** [comment]
Having this issue again. Request works fine with Alamofire, same request with RxAlamofire don't trigger the `.reponseData()`. Currently investigating.
