### ISSUE TITLE
I have updated my swift version from 3.2 to 4.2 and start getting error in api calling.

### ISSUE THREAD

**Issue by Mobifyi** [RxSwiftCommunity/RxAlamofire#152]
I am getting error after updating my swift versions from 3.2 to 4.2. Error is "RxAlamofireDomain error -1". Some time it getting successful and most of the time getting this error.

**Comment by sunshinejr** [comment]
@Mobifyi Can you try and get request/response logs from both versions (3.2, 4.2)?

**Comment by shraddha-patel-1891** [comment]
Hello @Mobifyi  
I have the same issue so have you got any solution regarding this?
if you have solution then please help me.
Thank you
