### ISSUE TITLE
Can I Add Korean translated version of README.md file?

### ISSUE THREAD

**Issue by della-padula** [RxSwiftCommunity/RxAlamofire#158]
I add the content which is translated to korean from english for REAMD.md file.
Can I commit this file and request merge?

**Comment by MarcSteven** [comment]
@della-padula  Hi, you can send PR and then if the author think it's cool , they can merge it into the master. Your contribution will make the project work well. Come on!

**Comment by della-padula** [comment]
I already send pull request, but the pipeline was failed. I just ONLY modify the README.md file. I don't know why the pipeline was failed.....

**Comment by MarcSteven** [comment]
Yeah, nothing ，  you can skip CI and then all will be passed @della-padula
