### ISSUE TITLE
Response difference between RxAlamofire and URLSession + Rx

### ISSUE THREAD

**Issue by DAEUN28** [RxSwiftCommunity/RxAlamofire#163]
I sent the request in two ways to the server that was implemented by the Spring.
I sent the request using URLSession + Rx and RxAlamofire, but different results were obtained.
The status code when using RxAlamofire was 400, and the status code when using URLSession + Rx was 200.
I tried to find the cause of the problem but couldn't find the cause.
I think only servers implemented with Spring have different results.
Is there a way to get a successful response using RxAlamofire?😂

Please refer to the attached photos.
<img width="1440" alt="image-20191127212709145" src="https://user-images.githubusercontent.com/45457678/69724783-f2b90b00-115f-11ea-8f44-f4bd99556d05.png">
<img width="1440" alt="image-20191127212733565" src="https://user-images.githubusercontent.com/45457678/69725247-0022c500-1161-11ea-9f90-2a0c0618b1db.png">

**Comment by sunshinejr** [comment]
Hey @DAEUN28. It seems to me that you are sending `JSON`-encoded parameters in the body of the `URLSession`+Rx request but `URL`-encoded parameters in the `RxAlamofire`'s request. Can you try using `JSONEncoding` in the `RxAlamofire` call as well and see if it helps?

**Comment by DAEUN28** [comment]
It's solved!! Thank you very much😆😆🥳
