### ISSUE TITLE
5.2 release does not build

### ISSUE THREAD

**Issue by peterlendvay** [RxSwiftCommunity/RxAlamofire#172]
Hi, 
 
5.2 release doesn't seem to build for us. We are using Carthage and the build fails with a lot of errors. I've tried downloading the source code from your github release page, and building it in XCode 11.4.1, but I get 33 errors. 

![image](https://user-images.githubusercontent.com/11329930/81914481-a492a980-95d1-11ea-9e8e-077c03805899.png)

Help would be appreciated, thanks!

**Comment by gonzo-oin** [comment]
Same bug here

**Comment by peterlendvay** [comment]
Is RxXAlamofire actively supported?
