### ISSUE TITLE
Usage of observer.onNext in Manager.rx_request method

### ISSUE THREAD

**Issue by RenGate** [RxSwiftCommunity/RxAlamofire#18]
In RxAlamofire there is a method [rx_request](https://github.com/RxSwiftCommunity/RxAlamofire/blob/develop/RxAlamofire/Source/RxAlamofire.swift#L338-L368) on Manager class that is used by other methods. 
I am concerned that a call to Observer.onNext method the way it is done right now (i.e., not from the a response handling closure) is making code like this
`Alamofire.Manager.sharedInstance.rx_request(.HEAD, "http://httpbin.org/status/200")
.subscribeNext { (request: Request) in
    print(request.response?.statusCode)
}`
to print nil instead of 200.
Am I missing something or does onNext must be called from response handling closure right before the call to onCompleted?

**Comment by RenGate** [comment]
Ok, now I understand that one need to call one of methods that use [Request.rx_result](https://github.com/RxSwiftCommunity/RxAlamofire/blob/develop/RxAlamofire/Source/RxAlamofire.swift#L703) to get an actual response right after it will be ready. Sorry for bothering.

**Comment by kzaher** [comment]
:)
