### ISSUE TITLE
No such module 'Alamofire' issue with XCode 11.5

### ISSUE THREAD

**Issue by enasaz9** [RxSwiftCommunity/RxAlamofire#180]
After updating my OS to Catalina 10.15.4 (19E287), and my Xcode to 11.5 
I'm getting this error whenever i'm trying to build my app
No such module 'Alamofire'

Podfile.lock snippet
```
  - Alamofire (4.9.1)
  - RxAlamofire (4.4.1):
    - RxAlamofire/Core (= 4.4.1)
  - RxAlamofire/Core (4.4.1):
    - Alamofire (~> 4.8)
    - RxSwift (~> 4.5)
  - RxCocoa (4.5.0):
    - RxSwift (>= 4.4.2, ~> 4.4)
  - RxDataSources (3.1.0):
    - Differentiator (~> 3.0)
    - RxCocoa (~> 4.0)
    - RxSwift (~> 4.0)
  - RxSwift (4.5.0)
```

**Comment by rynecheow** [comment]
Hi @enasaz9, am not sure what is wrong, as this might be more related to Alamofire itself looking at your issue. Could you share more here?
