### ISSUE TITLE
Add CI

### ISSUE THREAD

**Issue by bontoJR** [RxSwiftCommunity/RxAlamofire#27]
I would definitely like to add CI for RxAlamofire considering the increasing of people using/testing it.

Any recommendation @ashfurrow?

**Comment by ashfurrow** [comment]
I like [Circle CI](https://circleci.com) but Travis is good, too, I've just been leaning towards Circle more lately.

**Comment by bontoJR** [comment]
Circle CI is asking for an upgrade to run other over other repos, I don't know why... Travis is working now 🎉

**Comment by ashfurrow** [comment]
Weird!
