### ISSUE TITLE
Carthage fails to build with error citing cocoapods

### ISSUE THREAD

**Issue by genu1** [RxSwiftCommunity/RxAlamofire#30]
*** Building scheme "RxAlamofire-iOS" in RxAlamofire.xcworkspace
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution 📦\ Check\ Pods\ Manifest.lock /Users/***/Library/Developer/Xcode/DerivedData/RxAlamofire-dnklpqxrbiqsixffethmxfmjphai/Build/Intermediates/RxAlamofire.build/Release-iphoneos/RxAlamofire-iOS.build/Script-3CE028ADEF441613B86099C2.sh
(1 failure)

The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
A shell task failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	PhaseScriptExecution 📦\ Check\ Pods\ Manifest.lock /Users/robotmbp/Library/Developer/Xcode/DerivedData/RxAlamofire-dnklpqxrbiqsixffethmxfmjphai/Build/Intermediates/RxAlamofire.build/Release-iphoneos/RxAlamofire-iOS.build/Script-3CE028ADEF441613B86099C2.sh
(1 failure)

**Comment by genu1** [comment]
using 'carthage update --platform iOS'

**Comment by genu1** [comment]
in Cartfile 
`github "RxSwiftCommunity/RxAlamofire" "master"`

**Comment by keepingitneil** [comment]
+1 having the same issue.

**Comment by kyungkoo** [comment]
@genu1 Although I executed `carthage update --platform iOS` and `github "RxSwiftCommunity/RxAlamofire" "master"`, build error is occurred.

**Comment by YSDC** [comment]
+1 having the same issue.... It's really a problem, is anyone taking care of it?

**Comment by Vkt0r** [comment]
I don't know if someone is taking care of it, but it's a really problem as you said @YSDC , for now I'm working with previous release specifying in the Cartfile one specific commit.

**Comment by YSDC** [comment]
It's like no one cares about this issue, really not a good point for this lib. 

I wanted to push for it in my company (that is not a small one..) but the lake of support, and the number of issues that appears when you want to build (with carthage) or deploy to apple (raised because of this lib) is not at all something positive...

**Comment by orta** [comment]
Hey there people, you are welcome to give a helping hand, people who work on this repo may not have much knowledge on how to work with Carthage, PRs are, of course encouraged if you have that knowledge.

**Comment by solidcell** [comment]
I've opened PR #33 which fixes this issue.

**Comment by solidcell** [comment]
This works as of [`3.0.0-beta.1`](https://github.com/RxSwiftCommunity/RxAlamofire/tree/3.0.0-beta.1).  Someone with permissions should close it out.
