### ISSUE TITLE
how set Alamofire timeout

### ISSUE THREAD

**Issue by SeongBrave** [RxSwiftCommunity/RxAlamofire#31]
how set Alamofire timeout

**Comment by SeongBrave** [comment]
http://stackoverflow.com/questions/31095070/alamofire-does-not-respect-timeout-interval

class APIClient {
    var user = User()
    let alamoFireManager : Alamofire.Manager?
    let center = NSNotificationCenter.defaultCenter()


    init(){
        let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
        configuration.timeoutIntervalForRequest = 4 // seconds
        configuration.timeoutIntervalForResource = 4
        self.alamoFireManager = Alamofire.Manager(configuration: configuration)
    }

    func test(){
        //This does not respect the 4 second time out. Why?
        self.alamoFireManager!.request(.POST, CONSTANTS.APIEndpoint+"/test", parameters: parameters).responseJSON {
                        (req, res, json, error)  in
                        if let json = self.handleAPIResponse(req, res: res, json_data: json, error: error){
                        }
                    }
    }



and for RxAlamofire  how?

**Comment by titoaesj** [comment]
I have the same problem

**Comment by sergdort** [comment]
Are you guys sure that it's not Alamofire problem?

**Comment by titoaesj** [comment]
I think not @sergdort, the problem and the lack of support of RXAlamofire, I will use the Alamofire to solve my problem.

**Comment by freak4pc** [comment]
You need to set up a custom NSURLSessionConfiguration on your own AlamofireManager.

Swift 3 ex:
```swift
let configuration = URLSessionConfiguration.default
configuration.timeoutIntervalForResource = 5 // seconds

let alamofireManager = Alamofire.SessionManager(configuration: configuration)
```

This isn't a RxAlamofire issue, I agree with @sergdort. Probably something underlying since I dont notice any piece of code in RxAlamofire that affects the timeout.

**Comment by freak4pc** [comment]
Uhm I actually just realized it's always using the default session manager if I'm not mistaken.

https://github.com/RxSwiftCommunity/RxAlamofire/blob/master/Sources/RxAlamofire.swift#L78

@bontoJR perhaps it would be beneficial to allow setting a custom SessionManager for such purposes ?

**Comment by sergdort** [comment]
Guys, the test from of @SeongBrave has nothing to do with Rx..
I mean if this code does not respect timeout then it's not our scope of RxAlamofire:
```
self.alamoFireManager!.request(.POST, CONSTANTS.APIEndpoint+"/test", parameters: parameters).responseJSON {
                    (req, res, json, error)  in
                    if let json = self.handleAPIResponse(req, res: res, json_data: json, error: error){
                    }
                }
```

**Comment by sergdort** [comment]
@freak4pc what do you mean by setting custom `SessionManager` ?

**Comment by sergdort** [comment]
@freak4pc There is an option of using `rx` extension methods on any instance of [`SessionManager` ](https://github.com/RxSwiftCommunity/RxAlamofire/blob/master/RxAlamofire/RxAlamofire-iOS-Example/MasterViewController.swift#L155)

**Comment by freak4pc** [comment]
@sergdort oh sorry didn't notice it was just helper methods ... not focused today ;-)

**Comment by fodderkonoko** [comment]
exactly as @sergdort mentioned,
SessionManager is made Reactive in the RxAlamofire.
Therefore create your own SessionManager and then call the **rx** on it to make it reactive. Something like
`let sessionManager: SessionManager = {
            let configuration = URLSessionConfiguration.default
            configuration.httpAdditionalHeaders = SessionManager.defaultHTTPHeaders
            return SessionManager(configuration: configuration)
        }()        
        sessionManager.rx.request(method, url, parameters: parameters, encoding: encoding, headers: headers)`
