### ISSUE TITLE
Deploy to appstore failed

### ISSUE THREAD

**Issue by YSDC** [RxSwiftCommunity/RxAlamofire#32]
Did anyone ever tried to deploy an project archive that contains RxAlamofire? 

i got the following message from apple:

> Invalid Bundle - Do not submit apps with GCC-style coverage instrumentation enabled. Specifically, the following Xcode build settings should be disabled: Instrument Program Flow Generate Test Coverage Files

And if i try to modify these values or the bitecode parameter from 'yes' to 'no' then i cannot build it anymore.

**Comment by kzaher** [comment]
Hi @YSDC ,

there is `Enable code coverage support` turned on. I think that might be causing this issue.

I'll try to take a look at why Carthage integration is failing also, but will need some time.
