### ISSUE TITLE
No such module 'RxCocoa' using swift 3.0

### ISSUE THREAD

**Issue by guitcastro** [RxSwiftCommunity/RxAlamofire#42]
Hi,

I am trying to add RXAlamofire in my project using:

```
pod 'RxAlamofire', :git => 'https://github.com/RxSwiftCommunity/RxAlamofire.git', :branch => 'develop'
```

But I am getting `No such module 'RxCocoa'` in the import: 
```
import struct RxCocoa.Reactive
```

**Comment by RoryKelly** [comment]
I have the same problem any solution yet?

**Comment by felixk** [comment]
I have the same issue as well.

**Comment by kzaher** [comment]
We've made a 3.0.0-beta.1 pre-release, should work now.

**Comment by guitcastro** [comment]
it's working now! Thanks

**Comment by skyline75489** [comment]
I'm still getting this with 3.0.0-beta.1. Any thoughts?

**Comment by joaoh82** [comment]
What I did is I imported manually the rxalamofire.swift file and for some reason had to change this on the imports...

import RxCocoa
//import struct RxCocoa.Reactive
//import protocol RxCocoa.ReactiveCompatible

But it is working.
