### ISSUE TITLE
Workspace contains no schemes or anything

### ISSUE THREAD

**Issue by solidcell** [RxSwiftCommunity/RxAlamofire#45]
I'm trying to open the workspace on `develop` (currently https://github.com/RxSwiftCommunity/RxAlamofire/commit/6a6a3ec823a59c719da4d7710264e177a6411f09), however Xcode shows no files or schemes available.

I noticed that it happened with this commit @kzaher: https://github.com/RxSwiftCommunity/RxAlamofire/commit/19509a222418051fb3dfca8340714b210c9d93db

Maybe there's something I'm missing?

Here's a pre-`19509a2` screenshot and a post-`19509a2` screenshot:

<img width="838" alt="screen shot 2016-09-22 at 4 51 35 pm" src="https://cloud.githubusercontent.com/assets/309224/18753432/94e7af44-80e5-11e6-8cf0-266be5477739.png">
<img width="867" alt="screen shot 2016-09-22 at 4 52 44 pm" src="https://cloud.githubusercontent.com/assets/309224/18753433/94ecd2b2-80e5-11e6-8325-d027c446f715.png">

It's the same behavior on Xcode 7.3.1 and 8.0

**Comment by sergdort** [comment]
Hi, what workspace did you open, there are two

on in the root directory of the project and another on in `RxAlamofire` folder

**Comment by solidcell** [comment]
Ah, right you are, I was trying to open the root workspace before.  Thanks!
