### ISSUE TITLE
Carthage fails to fetch RxSwift

### ISSUE THREAD

**Issue by stanislavprokopov** [RxSwiftCommunity/RxAlamofire#46]
I have added `github "RxSwiftCommunity/RxAlamofire" "master"`, and when i run `carthage update` it fails:

`*** Fetching RxAlamofire
Parse error: unexpected trailing characters in line: github "ReactiveX/RxSwift" ~> 3.0.0-beta.1`

The issue here is that carthage does not support this style `3.0.0-beta.1` of version number, according to official documentation:

> Tags without any version number, or with any characters following the version number (e.g., 1.2-alpha-1) are currently unsupported, and will be ignored.

Please change the carthage RxSwift dependency definition to smth like this `github "ReactiveX/RxSwift" "3.0.0-beta.1"`

**Comment by kzaher** [comment]
Hi @stanislavprokopov ,

I've fixed this, I think this should work now. You will maybe need to clean Carthage cache :(

**Comment by stanislavprokopov** [comment]
@kzaher, thanks! That was quick. Now it works.
