### ISSUE TITLE
Carthage is building the project twice

### ISSUE THREAD

**Issue by solidcell** [RxSwiftCommunity/RxAlamofire#47]
I just realized that Carthage is building the project twice.  I haven't looked into it yet, but I'm planning to.  Just putting this out there in case anyone else gets to it first or knows why right off the bat.

``` shell
carthage update --platform ios
...
...
*** Building scheme "RxSwift-iOS" in Rx.xcworkspace
*** Building scheme "RxAlamofire-iOS" in RxAlamofire.xcworkspace
*** Building scheme "RxAlamofire-iOS" in RxAlamofire.xcworkspace
*** Building scheme "RxDataSources-iOS" in RxDataSources.xcworkspace
...
...
```

**Comment by kzaher** [comment]
Hi @solidcell ,

if you figure out anything, please share ...

**Comment by Ricardo1980** [comment]
Did you find the solution? I have the same problem.
