### ISSUE TITLE
progress() logic is incorrect

### ISSUE THREAD

**Issue by solidcell** [RxSwiftCommunity/RxAlamofire#48]
Before I make a PR, I wanted to verify I'm not missing something.  The logic for `progress()` is seemingly very wrong.  [This is the method in question.](https://github.com/RxSwiftCommunity/RxAlamofire/blob/86d8e62700540e30b9c371acf0424abb338397b2/Sources/RxAlamofire.swift#L858)
1.  The property `RxProgress.totalBytesWritten` is named for the opposite of what it actually does.  Shouldn't it be something like `RxProgress.bytesRemaining`?
2. The condition guarding `observer.onCompleted()` is wrong and will never be hit. Shouldn't it be: `rxProgress.bytesWritten == rxProgress.totalBytesExpectedToWrite` or something similar?  I imagine it was meant to be, but it was confused with the other property I mentioned in `#1` which is probably misnamed.

This is some sample output I get if I print the elements:

> RxProgress(bytesWritten: 0, totalBytesWritten: 0, totalBytesExpectedToWrite: 0)
> RxProgress(bytesWritten: 22015, totalBytesWritten: 23879, totalBytesExpectedToWrite: 45894)
> RxProgress(bytesWritten: 45894, totalBytesWritten: 0, totalBytesExpectedToWrite: 45894)

According to the current logic, `onCompleted` will never get executed.  The condition check (`rxProgress.totalBytesWritten >= rxProgress.totalBytesExpectedToWrite`) would result in the following:

> 0 >= 0 // not hit because it comes from `startWith` and not from `self.base.downloadProgress`
> 23879 >= 45894 // false
> 0 >= 45894 // false

I just figured I should ask first, since I figured someone must be using this already and must have noticed.  Although, maybe not, and there are no tests for it, so I can see how this fell through the cracks.

If others agree, I'll write tests and fix it.

**Comment by kzaher** [comment]
Hi @solidcell ,

I think you are right.

I believe it should be something like this:

```swift
return Observable.create { observer in
            self.base.downloadProgress { (progress) in
                let rxProgress = RxProgress(bytesWritten: progress.completedUnitCount,
                                            bytesRemaining: progress.totalUnitCount - progress.completedUnitCount,
                                            totalBytes: progress.totalUnitCount)
                observer.onNext(rxProgress)
                if rxProgress.bytesWritten >= rxProgress.totalBytes {
                    observer.onCompleted()
                }
            }
            return Disposables.create()
            }
            // warm up a bit :)
            .startWith(RxProgress(bytesWritten: 0, bytesRemaining: 0, totalBytes: 0))
```

**Comment by sergdort** [comment]
Hey, guys!  I wonder why do we need RxProgress at all? 
Why can't we use `Progress` from Alamofire? 
And since it used to be a `NSProgress` it has the same API in order to work with progress
E.g if you have multiple progresses you can combine them  into one in order to show progress of multiple tasks

**Comment by solidcell** [comment]
Yea, we could just get rid of it completely.  I'm on board.

**Comment by kzaher** [comment]
Hi guys,

@sergdort  I believe it's being used because `Progress` is a mutable object which is against element guidelines.

We'll also need to improve our RxAlamofire wrapper to not use `Request` object, but a immutable wrapper.

I still haven't find time to make those changes :(, but I'm planning to fix those issues since I believe it's causing problems understanding how RxAlamofire works.
