### ISSUE TITLE
Receiving "Ambiguous reference to member 'progress'" with download

### ISSUE THREAD

**Issue by digitaltoad** [RxSwiftCommunity/RxAlamofire#54]
When following the progress example, only modifying it for download I'm receiving this compiler error in regard to `request.rx.progress()` using Swift 3.0 and Xcode 8. The example for upload seems to work fine. I feel like this may be because `UploadRequest` inherits `DataRequest` but `DownloadRequest` inherits `Request`. I could possibly test this theory and send a PR if other eyes deem that the case.

Quick example:

``` Swift
_ = download(try! RxAlamofire.urlRequest(.get, stringURL), destination: destination)
    .flatMap { $0.rx.progress() }
```

**Comment by kzaher** [comment]
Hi @digitaltoad ,

this should be solved now.
