### ISSUE TITLE
Invalid framework with carthage

### ISSUE THREAD

**Issue by terietor** [RxSwiftCommunity/RxAlamofire#57]
If you use carthage in order to build RxAlamofire an invalid framework will be created.

The framework which will be created will work normally in the simulator and in devices but
if you try to create an archive of your application which contains RxAlamofire you will come across to two issues
1. XCode will crash 
2. ITC will complain about RxAlamofire embedded framework

I have investigated these issues and I have some information to share.

```
ls Carthage/Build/iOS/RxAlamofire.framework
Frameworks     
Headers    
Info.plist   
Modules      
RxAlamofire
libswiftRemoteMirror.dylib
```

`libswiftRemoteMirror.dylib` is responsible for the XCode crashes.
So we remove it and we try another archive.

This time ITC will complain about the structure of our framework.
So if we remove the `Frameworks` directory it will work.

Q: Why is RxAlamofire not working??
A: Carthage is building RxAlamofire from the `RxAlamofire.xcworkspace` and not from the `_.xcodeproj`. The  `RxAlamofire.xcworkspace` in the build settings it has `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=Yes` but it should be `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES=No`.

**Comment by kzaher** [comment]
Hi @terietor ,

I've pushed fix for this. If you figure out why Carthage is building the project from workspace, please let us know.

**Comment by terietor** [comment]
Hello,

@kzaher sorry I have missed your question.
If a scheme exists in a project and in a workspace  then carthage will try to build it from the workspace. Also it doesn't matter if your workspace is in the root directory of the repository or not.
