### ISSUE TITLE
Carthage update

### ISSUE THREAD

**Issue by MooYoo** [RxSwiftCommunity/RxAlamofire#58]
Hi，i import the two in my project：
github "RxSwiftCommunity/RxAlamofire" "3.0.0-rc.1"
github "RxSwiftCommunity/RxDataSources" "1.0.0-rc.1"

and carthage update， but failed，log below：

Could not pick a version for github "ReactiveX/RxSwift", due to mutually incompatible requirements:
	"3.0.0-beta.1" (github "RxSwiftCommunity/RxAlamofire")
	"3.0.0-rc.1" (github "RxSwiftCommunity/RxDataSources")

i found that in your "Cartfile.resolved"，it still point to 
"github "ReactiveX/RxSwift" "3.0.0-beta.1""

can you fixed it?

**Comment by kzaher** [comment]
@MooYoo 

```
github "RxSwiftCommunity/RxAlamofire" "3.0.0-rc.2"
```

**Comment by MooYoo** [comment]
@kzaher   than you very much~
