### ISSUE TITLE
dyld: Symbol not found

### ISSUE THREAD

**Issue by rusmichal** [RxSwiftCommunity/RxAlamofire#59]
Did I do something wrong with configuration?

http://stackoverflow.com/questions/40172231/ios-app-with-framework-crashed-on-device-dyld-symbol-not-found-xcode-8

**Comment by kzaher** [comment]
Hi @rusmichal ,

could you please try with latest 3.0.0 release?

**Comment by rusmichal** [comment]
I created new project and it works. thx
