### ISSUE TITLE
Please support iOS8

### ISSUE THREAD

**Issue by zeffon** [RxSwiftCommunity/RxAlamofire#63]
RxAlamofire is very nice for RxSwift.
Today I know that Alamofire4.1 has support iOS8.0, maybe RxAlamofire supports iOS8 is more nice.
Thanks.

**Comment by shams-ahmed** [comment]
Alamofire doing to drop iOS8 support in their next release, is there any reason now to maintain such code when it will be deprecated soon after?

**Comment by sergdort** [comment]
Yeah, I believe nothing should force us to drop iOS 8
Because Alamofire supports iOS 9.0
@kzaher I can make changes and publish new pod spec today, if you don't see any issues with this

**Comment by kzaher** [comment]
@sergdort If alamofire won't support iOS 8, then we can't either because package manager will complain.

**Comment by kzaher** [comment]
I think we can now support it, but not sure can we in future.

**Comment by sergdort** [comment]
Hm.. I see [here](https://github.com/Alamofire/Alamofire/blob/master/Alamofire.podspec#L11) and [here](https://github.com/Alamofire/Alamofire#requirements)
I think they won't drop iOS 8 at least in Alamofire 4.0, because this would be a breaking change :)

**Comment by shams-ahmed** [comment]
sound good, alamofire milestone 4.3.0 doesn't mention it, i guess it impossible to say how long they would do so...

**Comment by sergdort** [comment]
Hey guys, just published new version and pod spec should be fine now
