### ISSUE TITLE
Cartfile dependence version should update.

### ISSUE THREAD

**Issue by ufosky** [RxSwiftCommunity/RxAlamofire#64]
Update the version to support ios 8.0.

**Comment by sergdort** [comment]
Hi, @ufosky. Could you please clarify what do you mean by `dependence version`?

**Comment by ufosky** [comment]
Hi, @sergdort. The project deployment version is 9.0 and 10.0 like here: https://github.com/RxSwiftCommunity/RxAlamofire/blob/master/_.xcodeproj/project.pbxproj#L403
. You can search with word `IPHONEOS_DEPLOYMENT_TARGET` , it makes the framework cannot be used in project which deployment version is 8.0.
