### ISSUE TITLE
How to add retry logic

### ISSUE THREAD

**Issue by tosbaha** [RxSwiftCommunity/RxAlamofire#68]
Hi, I am trying to add retry logic but I can't make it work. `retry(3)` is ignored in the get function. However if I try to add retry outside of class it works. I will appreciate if you can help me solve this problem. I think also adding documentation for retry logic can be super helpful. Thanks.

```swift
class ApiClient {
    var baseURL:String

    init(baseURL:String) {
        self.baseURL = baseURL
    }

    func get(type:ApiType) -> Observable<[Post]>{
        return RxAlamofire
            .request(.get, baseURL + "/someurl") //doesn't exist
            .flatMap {
            $0.validate(statusCode: 200..<300)
            .rx.json()
            }.retry(3) // this is ignored
            .map{(data) -> [Post] in
                var posts = [Post]()
                // parse it
                return posts
        }
    }
}
    let apiClient = ApiClient(baseURL: "https://jsonplaceholder.typicode.com")
    apiClient.get(type: .posts)
      // .retry(3) //if I add retry logic here it works.
        .subscribe(onNext:  { [weak self] posts in
            self?.objects = posts
            self?.tableView.reloadData()

            }, onError: { error in
                print(error)

        }).addDisposableTo(disposablebag)
```

**Comment by kzaher** [comment]
Hm,

I think this should work, weird.

**Comment by tosbaha** [comment]
I really don't know the reason but below code also works

```swift
func get(type:ApiType) ->Observable<[Post]> {
        return json(.get, baseURL + "/someurl")
            .retry(3)
            .map{ responseData in
            var posts = [Post]()
                // parse it

            return posts
        }
    }
```

**Comment by freak4pc** [comment]
Hey @tosbaha 
I'm sorry for the 4 month late reply here but I'm trying to help clean up the issue backlog ;) 

The reason here is that RxAlamofire.request doesn't return an error for non-200 HTTP codes. I would argue this is a wrong approach, but this is following the same design as Alamofire itself. 

Using SessionManager.rx.json would fire an error for a failed request. 

See here: https://github.com/RxSwiftCommunity/RxAlamofire/issues/72#issuecomment-274797043

**Comment by tosbaha** [comment]
I am not good at math but I think it is 5 months :) Anyway, I moved to Moya since I felt this project wasn't maintained. Best regards.

**Comment by freak4pc** [comment]
Yeah it said January and it's may and I haven rounded up ;)
