### ISSUE TITLE
Add Carthage support

### ISSUE THREAD

**Issue by sboisson** [RxSwiftCommunity/RxAlamofire#7]
With the the current source, Carthage outputs error:

    Dependency "RxAlamofire" has no shared framework schemes

**Comment by orta** [comment]
Would you like to see if you can get a PR fixing it? You might have more knowledge in the area.

**Comment by libec** [comment]
Just in case @sboisson doesn't feel like it (or went AFK for a few days) 🙈

**Comment by bontoJR** [comment]
It seems this is working since a while, if somebody has any related problem, please consider re-open this.

**Comment by henjue** [comment]
*** Building scheme "RxAlamofire-Carthage" in RxAlamofire.xcworkspace
2016-04-16 21:14:52.714 xcodebuild[39436:786146] [MT] PluginLoading: Required plug-in compatibility UUID ACA8656B-FEA8-4B6D-8E4A-93F4C95C362C for plug-in at path '~/Library/Application Support/Developer/Shared/Xcode/Plug-ins/XcodeColors.xcplugin' not present in DVTPlugInCompatibilityUUIDs

**Comment by libec** [comment]
Hey @henjue , this is not directly related to RxAlamofire or Carthage. This basically means that plugin is confused by your Xcode version or some other magic. You can rebuild the plugin or add the version to DVTPlugInCompatibilityUUIDs (see more at https://gist.github.com/neonichu/9487584 ) or just ignore the warning 😅

**Comment by henjue** [comment]
@libec thk
