### ISSUE TITLE
non 200 responses do not result in RxSwift onError events.

### ISSUE THREAD

**Issue by dustin-graham** [RxSwiftCommunity/RxAlamofire#72]
When I get a 401 back from my server, my RxAlamofire calls run as if the request was successful. I can see that I get a 401 in the response but it still wants me to process the response in the same location where I'm anticipating parsing my JSON. Is this by design or do I have something misconfigured?

```
func getNeighborhood() -> Observable<ResponseNeighborhood> {
        return sessionManager.rx.responseJSON(.get, apiHost + "/neighborhood").map { response, json in
// execution still arrives here even though the response object statusCode is 401. This seems wrong.
            guard
                let neighborhoodJson = json as? JSON,
                let neighborhood = ResponseNeighborhood(json: neighborhoodJson)
                else {
                throw self.checkResponseError(statusCode: response.statusCode, json: json) ?? APIError.illegalState
            }

            return neighborhood
        }
    }
```

When I subscribe I get a `.next` event which gives me an empty result in my case because my JSON parsing code encountered an error when trying to process the 401.

```
        self.sw.neighborhood().subscribe { e in
            switch e {
            case .next(let neighborhood):
                // on errrors, I end up with an empty neighborhood because JSON parsing failed when my parsing code received a result on a 401
                print(neighborhood.count)
            case .error(let error):
                // I feel like a 401 response is an error and it should end up here
                print(error)
            case .completed:
                print("completed")
            }
        }
```

I suppose this might be by design. Perhaps it is supposed to be my responsibility to inspect the response for errors and handle it accordingly. I'm writing an extension now to detect any non 200 response and send a `.error` event with the response attached to the error. But I'd like to know if this is intended behavior and if not, what I can do to get error code requests to result in `.error` events.

Thanks.

**Comment by turekj** [comment]
When using `responseJSON` (and other `responseXXX`) method the status code is not validated by design. This is consistent with Alamofire approach:

> By default, Alamofire treats any completed request to be successful, regardless of the content of the response. Calling validate before a response handler causes an error to be generated if the response had an unacceptable status code or MIME type.

However, you can still use the `json` method which validates the response prior it is forwarded to your observer:

```
SessionManager.default.rx.json(.get, "https://api.github.com/user/orgs")
            .subscribe(onError: {
                print("Error: \($0)")
            }).addDisposableTo(disposeBag)
```

This will print out:

```
Error: responseValidationFailed(Alamofire.AFError.ResponseValidationFailureReason.unacceptableStatusCode(401))
```

Hope it helps :)
