### ISSUE TITLE
Completion handler will result in an observable that is always on the main thread

### ISSUE THREAD

**Issue by WesleyHilhorst** [RxSwiftCommunity/RxAlamofire#75]
`mySessionManager.rx.download` does not have any option to set a custom queue. This results in the completionHandler to be called on the main thread. This might give unexpected results when chaining.

**Comment by WesleyHilhorst** [comment]
It will always return to the main thread because thats how RxAlamofire works. So I could force the process to go back to a background thread. Its just that the context switch which is happening is something I would like to prevent from happening. 

In general its just unexpected behavior. Simply because Rx is controlling what thread the observable is running on with for example the observeOn method.

As far as I know, Alamofire does accept adding a custom queue for the response. Maybe this is something that could be looked at?

**Comment by Chhuon** [comment]
Hello

**Comment by freak4pc** [comment]
@WesleyHilhorst AFAIK the point of Rx is to be a centralized method for controlling flow. 
Dispatching tasks into queues (GCD/DispatchQueue) is wrapped in Rx so you don't need to think about it. Why does switching to a background scheduler not a viable solution for you?

**Comment by freak4pc** [comment]
@WesleyHilhorst I just went through the download method you were referring to, It doesn't state any Scheduler/Thread to begin with. So again I'm confused as to why working on a different Scheduler be an issue here?

**Comment by WesleyHilhorst** [comment]
I looked very quickly to whatever it was I meant at the time. I cannot find the code that was causing the context switch (at least in the current Alamofire/RxAlamofire combination).

If I recall correctly, the download method that RxAlamofire called within Alamofire had a completionhandler queue. RxAlamofire did not set this queue. This caused Alamofire to return back to the main thread.

**Comment by freak4pc** [comment]
Is this still an issue right now? And if yes, do you have code to reproduce the issue ? Have you tried using observeOn / subscribeOn to change the work flow ?

**Comment by WesleyHilhorst** [comment]
I have tried that. The issue with using observeOn / subscribeOn, is that a context switch still takes place. Which isn't really necessary. The idea of Rx is that internally, it doesn't change threads like that. Hence the unexpected behaviour.

If I have some more time, I will check if the issue is still an issue. Might be after WWDC though.
