### ISSUE TITLE
How do I use RxAlamofire with URLRequestConvertible?

### ISSUE THREAD

**Issue by kizitonwose** [RxSwiftCommunity/RxAlamofire#81]
I am trying to use RxAlamofire with a URLRequestConvertible router enum. I can see that this feature was added in #69 but for some reason, the methods are not available for me to use, the ones I have all take a URLConvertible so I have to cast my URLRequestConvertible as URLConvertible.  Is this the right way to do this? 

Edit: I'm also facing issue #78 the method in RxAlamofire which should take a URLRequestConvertible as the only parameter keeps saying it's missing argument for second parameter.

**Comment by freak4pc** [comment]
Hey @kizitonwose 
Can you please provide a reproducible project or code sample causing the issue?

**Comment by kizitonwose** [comment]
Hi @freak4pc 
The sample code that reproduces this issue is now available [here](https://github.com/kizitonwose/rxalamofire-bug-sample)

**Comment by freak4pc** [comment]
Sorry I just realized you are referring to URLRequestConvertible and not URLConvertible. It's currently not part of the code but I don't see why we can't add that.

**Comment by kizitonwose** [comment]
But [this method](https://github.com/RxSwiftCommunity/RxAlamofire/blob/master/Sources/RxAlamofire.swift#L94) seems to take a URLRequestConvertible as the only parameter.

**Comment by freak4pc** [comment]
Yup, @kizitonwose you're absolutely correct. 
This code is working but the issue is there was no new version created since so you're getting old code. 

Let me see if I can fix this up real quick :)

**Comment by freak4pc** [comment]
Ok @kizitonwose 
Quickes fix is changing your `Podfile` to: 
`pod 'RxAlamofire', :git => 'https://github.com/RxSwiftCommunity/RxAlamofire.git'`

@kzaher / @sergdort I'm not sure who has Pod access (I believe I don't) but a new version is needed ... the last one was over 6 months ago :)

**Comment by kizitonwose** [comment]
@freak4pc Yes, that works. Thanks! 
I want to close the issue but I'm guessing it would be better to keep it till a new version is released.

**Comment by freak4pc** [comment]
Let's keep this open until the guys answer. Thanks for the cooperation @kizitonwose !

**Comment by kizitonwose** [comment]
Alright.

**Comment by sergdort** [comment]
Hey guys will try to find time tomorrow and publish new version

**Comment by freak4pc** [comment]
Thanks @sergdort !

3.0.3 is out! 
https://github.com/RxSwiftCommunity/RxAlamofire/tree/3.0.3
