### ISSUE TITLE
How to refresh Token with RxAlamofire?

### ISSUE THREAD

**Issue by Bruce9487** [RxSwiftCommunity/RxAlamofire#85]
I have a problem about token expired then I get error response. 
So, I refresh the api token when I get error response and then how to recall api again?
I search for the refrsh token sample, and I find none about this information.
Have any idea to do this? Thanks.

https://stackoverflow.com/questions/46392868/how-to-refresh-api-authorization-token-using-alamofire-rxswift

**Comment by freak4pc** [comment]
@Bruce9487 This doesn't sound like a RxAlamofire but something perhaps relating to your observable chain. You also didn't provide any code so it's pretty impossible to help this way.

**Comment by freak4pc** [comment]
OP didn't provide response in a long time.
