### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by scoreyou** [RxSwiftCommunity/RxAlamofire#90]
I can't specify rxAlamofire pod in my podspec as dependency via :branch and :commit, so please make a new release with XCode9 and swift4 support.

**Comment by krin-san** [comment]
Why can't you use a branch instead tag? Actually it works good, but you have to define `:git` repo url too:
```
pod 'RxAlamofire', :git => 'https://github.com/RxSwiftCommunity/RxAlamofire', :branch => 'master'
```
But yeah, would be nice to create a new "Pre-Release" tag.

**Comment by scoreyou** [comment]
@krin-san it does not work when I try to define dependency in podspec (not podfile).

**Comment by keyfun** [comment]
please add a tag for swift 4 support. Thanks.

**Comment by sergdort** [comment]
🎉  Congrats

 🚀  RxAlamofire (4.0.0-rc.0) successfully published
 📅  October 10th, 21:46
 🌎  https://cocoapods.org/pods/RxAlamofire
 👍  Tell your friends!

I've pushed the spec :)
