### ISSUE TITLE
Is it possible to use this library with Swift 3.2?

### ISSUE THREAD

**Issue by mbopp** [RxSwiftCommunity/RxAlamofire#94]
Using Carthage.  Would like to avoid moving to Swift 4 for now if possible.  Or is it a lost cause?

**Comment by freak4pc** [comment]
Just closing issues here, sorry for the delay but there is no issue with using Carthage with a 3.2 version. 

3.0.3 should be the latest Swift 3 release. https://github.com/RxSwiftCommunity/RxAlamofire/tree/3.0.3
