### ISSUE TITLE
How to cancel previous request using RxAlamofire?

### ISSUE THREAD

**Issue by Bruce9487** [RxSwiftCommunity/RxAlamofire#95]
I want to cancel the previous request using RxAlamofire.
But I don't know where to call the cancel function.
I have a searchBar, and I call the API in function "textdidchange".
So, I want to cancel the previous request and call the API with new parameters.
Have any suggestion to help me?
Thanks.

[https://stackoverflow.com/questions/47746033/how-to-cancel-previous-request-using-rxalamofire](url)

**Comment by freak4pc** [comment]
You would use `flatMapLatest`. 
It would dispose (thereby cancelling) any pending requests and make a new one from the **latest** emitted observable in the chain.

This isn't Alamofire specific. Please read the official documentation, and also this might be a good resource: https://www.raywenderlich.com/158205/rxswift-transforming-operators

Good luck!
